### ISSUE TITLE
Marriage time and place run in

### ISSUE THREAD

**Issue by nigelhorne** [mikkelee/genealogytree-mkgraph#3]
When it prints the time and place of marriages have no space between them so that the last digit of the year is right next to the first character of the place.

**Comment by mikkelee** [comment]
That is likely because the marriage information is displayed unformatted.

If you're using the default setting (`--marriage family`), you'll need to set up `label options`, see section _8.4 Edge Labels_ in the genealogytree documentation. Try this in your .tex file (and edit to suit your needs):

```latex
\gtrset{
	label options={
		fill=white,
		node font=\tiny,
		inner sep=0.5mm,
		draw=green!30!black
	},
}
```

If you're using `--marriage proband` or `spouse`, see section _7.5 Formatting the Node Data_ in the genealogytree documentation. Example:

```latex
\gtrset{
	database format=full marriage below,
}
```

**Comment by mikkelee** [comment]
Is this still an issue? If so, please send the files to me and reopen.

**Comment by nigelhorne** [comment]
I've actually been working around it by manually editing the tex file to put a space in, thus I change

`database={marriage = {1883-06-09}{Margate}}]`

to

`database={marriage = {1883-06-09} {Margate}}]`

Though it's a pain, it does work.

**Comment by mikkelee** [comment]
That shouldn't be necessary if you use the edge label options from genealogytree.
